# Generated by Django 5.2.8 on 2025-11-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='entry',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
        migrations.AddField(
            model_name='entry',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], default=5, verbose_name='Рейтинг'),
        ),
    ]
