# Generated by Django 5.2.8 on 2025-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_entry_options_entry_is_favorite_entry_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, max_length=300, verbose_name='Теги (через запятую)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='country',
            field=models.CharField(choices=[('AF', 'Афганистан'), ('AX', 'Аландские острова'), ('AL', 'Албания'), ('DZ', 'Алжир'), ('AR', 'Аргентина'), ('AM', 'Армения'), ('AU', 'Австралия'), ('AT', 'Австрия'), ('AZ', 'Азербайджан'), ('BH', 'Бахрейн'), ('BD', 'Бангладеш'), ('BY', 'Беларусь'), ('BE', 'Бельгия'), ('BR', 'Бразилия'), ('BG', 'Болгария'), ('CA', 'Канада'), ('CN', 'Китай'), ('CO', 'Колумбия'), ('HR', 'Хорватия'), ('CU', 'Куба'), ('CZ', 'Чехия'), ('DK', 'Дания'), ('EG', 'Египет'), ('EE', 'Эстония'), ('FI', 'Финляндия'), ('FR', 'Франция'), ('GE', 'Грузия'), ('DE', 'Германия'), ('GR', 'Греция'), ('HU', 'Венгрия'), ('IS', 'Исландия'), ('IN', 'Индия'), ('ID', 'Индонезия'), ('IR', 'Иран'), ('IQ', 'Ирак'), ('IE', 'Ирландия'), ('IL', 'Израиль'), ('IT', 'Италия'), ('JP', 'Япония'), ('JO', 'Иордания'), ('KZ', 'Казахстан'), ('KE', 'Кения'), ('KR', 'Южная Корея'), ('KW', 'Кувейт'), ('LV', 'Латвия'), ('LB', 'Ливан'), ('LT', 'Литва'), ('MY', 'Малайзия'), ('MX', 'Мексика'), ('MA', 'Марокко'), ('NL', 'Нидерланды'), ('NZ', 'Новая Зеландия'), ('NO', 'Норвегия'), ('PK', 'Пакистан'), ('PE', 'Перу'), ('PH', 'Филиппины'), ('PL', 'Польша'), ('PT', 'Португалия'), ('QA', 'Катар'), ('RO', 'Румыния'), ('RU', 'Россия'), ('SA', 'Саудовская Аравия'), ('RS', 'Сербия'), ('SG', 'Сингапур'), ('SK', 'Словакия'), ('SI', 'Словения'), ('ES', 'Испания'), ('SE', 'Швеция'), ('CH', 'Швейцария'), ('SY', 'Сирия'), ('TW', 'Тайвань'), ('TH', 'Таиланд'), ('TR', 'Турция'), ('UA', 'Украина'), ('AE', 'ОАЭ'), ('GB', 'Великобритания'), ('US', 'США'), ('UY', 'Уругвай'), ('UZ', 'Узбекистан'), ('VN', 'Вьетнам')], max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(verbose_name='Впечатления'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='dish',
            field=models.CharField(max_length=200, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг'),
        ),
    ]
